version: '3.8'

services:
  mysql-db-algamoneyapi:
    image: mysql:8.0
    container_name: mysql_alagamoney_api
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: algamoneyapi
    ports:
      - "3306:3306"
    cap_add:
      - SYS_NICE  # Desabilitar o aviso "mbind: Operation not permitted"
